language: c

before_install:
 - git submodule update --init --recursive

env:
 - WITHZFS=false
 - WITHZFS=true

script: ./buildnb.sh -qq $(${WITHZFS} && echo zfs) buildrump tests

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
